// Generated by Selenium IDE
package org.ual.cnsa.jme418;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.*;
import org.openqa.selenium.firefox.*;
import org.openqa.selenium.support.ui.*;
import java.time.Duration;
import java.util.*;

public class EditProfileTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
	int browser = 0; // 0: firefox, 1: chrome...
	Boolean headless = true;

	switch (browser) {
	  case 0: // firefox
		// WebDriverManager.firefoxdriver().setup();
		FirefoxOptions firefoxOptions = new FirefoxOptions();
		if (headless) firefoxOptions.addArguments("-headless");
		driver = new FirefoxDriver(firefoxOptions);
	
		break;
	  case 1: // chrome
		// WebDriverManager.chromedriver().setup();
		ChromeOptions chromeOptions = new ChromeOptions();
		if (headless) chromeOptions.addArguments("--headless=new");
		driver = new ChromeDriver(chromeOptions);
	
		break;
	  default:
		fail("Please select a browser");
		break;
	}

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void editProfile() {
    // Test name: editProfile
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://webapps.cnsa2025-jme418.tech/");
    // 2 | setWindowSize | 1368x759 | 
    driver.manage().window().setSize(new Dimension(1368, 759));
    // 3 | click | xpath=//a[contains(text(),'Sign up')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign up\')]")).click();
    // 4 | type | id=full-name | Joaquín Murcia Escánez
    driver.findElement(By.id("full-name")).sendKeys("Joaquín Murcia Escánez");
    // 5 | executeScript | return new Date().getTime() + "@gmail.com"; | storedMail
    vars.put("storedMail", js.executeScript("return new Date().getTime() + \"@gmail.com\";"));
    // 6 | type | id=email-address | ${storedMail}
    driver.findElement(By.id("email-address")).sendKeys(vars.get("storedMail").toString());
    // 7 | type | id=password | jme418
    driver.findElement(By.id("password")).sendKeys("jme418");
    // 8 | type | id=confirm-password | jme418
    driver.findElement(By.id("confirm-password")).sendKeys("jme418");
    // 9 | click | id=terms-agreement | 
    driver.findElement(By.id("terms-agreement")).click();
    // 10 | click | xpath=//button[@type='submit'] | 
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    // 11 | waitForElementNotPresent | xpath=//h1[contains(.,'Sign in to your account')] | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.invisibilityOfElementLocated(By.xpath("//h1[contains(.,\'Sign in to your account\')]")));
      try {
      	Thread.sleep(500);
      } catch (InterruptedException e) {
      	e.printStackTrace();
      }
    }
    // 12 | assertText | xpath=//h1 | Welcome!
    assertEquals("Welcome!", driver.findElement(By.xpath("//h1")).getText());
    // 13 | click | id=header-account-menu-link | 
    driver.findElement(By.id("header-account-menu-link")).click();
    // 14 | click | xpath=//a[contains(text(),'Settings')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Settings\')]")).click();
    // 15 | click | xpath=//a[contains(text(),'Edit profile')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Edit profile\')]")).click();
    // 16 | executeScript | return new Date().getTime() + "@gmail.com"; | storedMail
    vars.put("storedMail", js.executeScript("return new Date().getTime() + \"@gmail.com\";"));
    // 17 | type | id=email-address | ${storedMail}
    //driver.findElement(By.id("email-address")).sendKeys(vars.get("storedMail").toString());
    {
      WebElement input = driver.findElement(By.id("email-address"));
      String storedMail = vars.get("storedMail").toString();
        
      js.executeScript(
        "arguments[0].value = arguments[1]; " +
        "arguments[0].dispatchEvent(new Event('input', { bubbles: true })); " +
        "arguments[0].dispatchEvent(new Event('change', { bubbles: true }));",
        input, storedMail
      );
    }
    // 18 | click | xpath=//button | 
    driver.findElement(By.xpath("//button")).click();
    // 19 | assertText | xpath=//div[3]/div[2]/strong | ${storedMail}
    {
	  WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
	  wait.until(ExpectedConditions.invisibilityOfElementLocated(By.xpath("//button")));

	  assertEquals(vars.get("storedMail").toString(), driver.findElement(By.xpath("//div[3]/div[2]/strong")).getText());
    }
    // 20 | click | id=header-account-menu-link | 
    driver.findElement(By.id("header-account-menu-link")).click();
    // 21 | click | xpath=//a[contains(text(),'Sign out')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign out\')]")).click();
    // 22 | type | xpath=//input[@type='email'] | ${storedMail}
    driver.findElement(By.xpath("//input[@type=\'email\']")).sendKeys(vars.get("storedMail").toString());
    // 23 | type | xpath=//input[@type='password'] | jme418
    driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("jme418");
    // 24 | click | xpath=//button | 
    driver.findElement(By.xpath("//button")).click();
    // 25 | waitForElementNotPresent | xpath=//h1[contains(.,'Sign in to your account')] | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.invisibilityOfElementLocated(By.xpath("//h1[contains(.,\'Sign in to your account\')]")));
      try {
      	Thread.sleep(500);
      } catch (InterruptedException e) {
      	e.printStackTrace();
      }
    }
    // 26 | assertText | xpath=//h1 | Welcome!
    assertEquals("Welcome!", driver.findElement(By.xpath("//h1")).getText());
    // 27 | click | id=header-account-menu-link | 
    driver.findElement(By.id("header-account-menu-link")).click();
    // 28 | click | xpath=//a[contains(text(),'Sign out')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign out\')]")).click();
    // 29 | assertText | xpath=//h1 | Sign in to your account
    assertEquals("Sign in to your account", driver.findElement(By.xpath("//h1")).getText());
  }
  @Test
  public void editProfileNotValid() {
    // Test name: editProfileNotValid
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://webapps.cnsa2025-jme418.tech/");
    // 2 | setWindowSize | 1368x759 | 
    driver.manage().window().setSize(new Dimension(1368, 759));
    // 3 | click | xpath=//a[contains(text(),'Sign up')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign up\')]")).click();
    // 4 | type | id=full-name | Joaquín Murcia Escánez
    driver.findElement(By.id("full-name")).sendKeys("Joaquín Murcia Escánez");
    // 5 | executeScript | return new Date().getTime() + "@gmail.com"; | storedMail
    vars.put("storedMail", js.executeScript("return new Date().getTime() + \"@gmail.com\";"));
    // 6 | type | id=email-address | ${storedMail}
    driver.findElement(By.id("email-address")).sendKeys(vars.get("storedMail").toString());
    // 7 | type | id=password | jme418
    driver.findElement(By.id("password")).sendKeys("jme418");
    // 8 | type | id=confirm-password | jme418
    driver.findElement(By.id("confirm-password")).sendKeys("jme418");
    // 9 | click | id=terms-agreement | 
    driver.findElement(By.id("terms-agreement")).click();
    // 10 | click | xpath=//button[@type='submit'] | 
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    // 11 | waitForElementNotPresent | xpath=//h1[contains(.,'Sign in to your account')] | 30000
    {
	  WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
	  wait.until(ExpectedConditions.invisibilityOfElementLocated(By.xpath("//h1[contains(.,\'Sign in to your account\')]")));
	  try {
		Thread.sleep(500);
	  } catch (InterruptedException e) {
		e.printStackTrace();
	  }
    }
    // 12 | assertText | xpath=//h1 | Welcome!
    assertEquals("Welcome!", driver.findElement(By.xpath("//h1")).getText());
    // 13 | click | id=header-account-menu-link | 
    driver.findElement(By.id("header-account-menu-link")).click();
    // 14 | click | xpath=//a[contains(text(),'Settings')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Settings\')]")).click();
    // 15 | click | xpath=//a[contains(text(),'Edit profile')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Edit profile\')]")).click();
    // 16 | executeScript | return " "; | storedMail
    //vars.put("storedMail", js.executeScript("return \" \";"));
    // 17 | type | id=email-address | ${storedMail}
    {
      WebElement input = driver.findElement(By.id("email-address"));
      js.executeScript(
        "arguments[0].value = ''; " +
        "arguments[0].dispatchEvent(new Event('input', { bubbles: true })); " +
        "arguments[0].dispatchEvent(new Event('change', { bubbles: true }));",
        input
      );
    }
    // 18 | click | xpath=//button | 
    driver.findElement(By.xpath("//button")).click();
    // 19 | assertText | xpath=//div[2]/div/div | Please enter a valid email address.
    assertEquals("Please enter a valid email address.", driver.findElement(By.xpath("//div[2]/div/div")).getText());
    // 20 | click | id=header-account-menu-link | 
    driver.findElement(By.id("header-account-menu-link")).click();
    // 21 | click | xpath=//a[contains(text(),'Sign out')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign out\')]")).click();
    // 22 | assertText | xpath=//h1 | Sign in to your account
    assertEquals("Sign in to your account", driver.findElement(By.xpath("//h1")).getText());
  }
}
