// Generated by Selenium IDE
package org.ual.cnsa.jme418;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.*;
import org.openqa.selenium.firefox.*;
import org.openqa.selenium.support.ui.*;
import java.time.Duration;
import java.util.*;

public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
	int browser = 0; // 0: firefox, 1: chrome...
	Boolean headless = true;

	switch (browser) {
	  case 0: // firefox
		WebDriverManager.firefoxdriver().setup();
		FirefoxOptions firefoxOptions = new FirefoxOptions();
		if (headless) firefoxOptions.addArguments("-headless");
		driver = new FirefoxDriver(firefoxOptions);
	
		break;
	  case 1: // chrome
		WebDriverManager.chromedriver().setup();
		ChromeOptions chromeOptions = new ChromeOptions();
		if (headless) chromeOptions.addArguments("--headless=new");
		driver = new ChromeDriver(chromeOptions);
	
		break;
	  default:
		fail("Please select a browser");
		break;
	}

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    // Test name: login
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://webapps.cnsa2025-jme418.tech/");
    // 2 | setWindowSize | 1368x759 | 
    driver.manage().window().setSize(new Dimension(1368, 759));
    // 3 | click | xpath=//a[contains(text(),'Sign up')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign up\')]")).click();
    // 4 | type | id=full-name | Joaquín Murcia Escánez
    driver.findElement(By.id("full-name")).sendKeys("Joaquín Murcia Escánez");
    // 5 | executeScript | return new Date().getTime() + "@gmail.com"; | storedMail
    vars.put("storedMail", js.executeScript("return new Date().getTime() + \"@gmail.com\";"));
    // 6 | type | id=email-address | ${storedMail}
    driver.findElement(By.id("email-address")).sendKeys(vars.get("storedMail").toString());
    // 7 | type | id=password | jme418
    driver.findElement(By.id("password")).sendKeys("jme418");
    // 8 | type | id=confirm-password | jme418
    driver.findElement(By.id("confirm-password")).sendKeys("jme418");
    // 9 | click | id=terms-agreement | 
    driver.findElement(By.id("terms-agreement")).click();
    // 10 | click | xpath=//button[@type='submit'] | 
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    // 11 | waitForElementNotPresent | xpath=//h1[contains(.,'Sign in to your account')] | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.invisibilityOfElementLocated(By.xpath("//h1[contains(.,\'Sign in to your account\')]")));
      try {
      	Thread.sleep(500);
      } catch (InterruptedException e) {
      	e.printStackTrace();
      }
    }
    // 12 | assertText | xpath=//h1 | Welcome!
    assertEquals("Welcome!", driver.findElement(By.xpath("//h1")).getText());
    // 13 | click | id=header-account-menu-link | 
    driver.findElement(By.id("header-account-menu-link")).click();
    // 14 | click | xpath=//a[contains(text(),'Sign out')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign out\')]")).click();
    // 15 | assertText | xpath=//h1 | Sign in to your account
    assertEquals("Sign in to your account", driver.findElement(By.xpath("//h1")).getText());
    // 16 | click | xpath=//a[contains(text(),'Log in')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Log in\')]")).click();
    // 17 | type | xpath=//input[@type='email'] | ${storedMail}
    driver.findElement(By.xpath("//input[@type=\'email\']")).sendKeys(vars.get("storedMail").toString());
    // 18 | type | xpath=//input[@type='password'] | jme418
    driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("jme418");
    // 19 | click | xpath=//button | 
    driver.findElement(By.xpath("//button")).click();
    // 20 | waitForElementNotPresent | xpath=//h1[contains(.,'Sign in to your account')] | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.invisibilityOfElementLocated(By.xpath("//h1[contains(.,\'Sign in to your account\')]")));
      try {
      	Thread.sleep(500);
      } catch (InterruptedException e) {
      	e.printStackTrace();
      }
    }
    // 21 | assertText | xpath=//h1 | Welcome!
    assertEquals("Welcome!", driver.findElement(By.xpath("//h1")).getText());
    // 22 | click | id=header-account-menu-link | 
    driver.findElement(By.id("header-account-menu-link")).click();
    // 23 | click | xpath=//a[contains(text(),'Sign out')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign out\')]")).click();
    // 24 | assertText | xpath=//h1 | Sign in to your account
    assertEquals("Sign in to your account", driver.findElement(By.xpath("//h1")).getText());
  }
  @Test
  public void loginNotValid() {
    // Test name: loginNotValid
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://webapps.cnsa2025-jme418.tech/");
    // 2 | setWindowSize | 1368x759 | 
    driver.manage().window().setSize(new Dimension(1368, 759));
    // 3 | click | xpath=//a[contains(text(),'Sign up')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign up\')]")).click();
    // 4 | type | id=full-name | Joaquín Murcia Escánez
    driver.findElement(By.id("full-name")).sendKeys("Joaquín Murcia Escánez");
    // 5 | executeScript | return new Date().getTime() + "@gmail.com"; | storedMail
    vars.put("storedMail", js.executeScript("return new Date().getTime() + \"@gmail.com\";"));
    // 6 | type | id=email-address | ${storedMail}
    driver.findElement(By.id("email-address")).sendKeys(vars.get("storedMail").toString());
    // 7 | type | id=password | jme418
    driver.findElement(By.id("password")).sendKeys("jme418");
    // 8 | type | id=confirm-password | jme418
    driver.findElement(By.id("confirm-password")).sendKeys("jme418");
    // 9 | click | id=terms-agreement | 
    driver.findElement(By.id("terms-agreement")).click();
    // 10 | click | xpath=//button[@type='submit'] | 
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    // 11 | waitForElementNotPresent | xpath=//h1[contains(.,'Sign in to your account')] | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.invisibilityOfElementLocated(By.xpath("//h1[contains(.,\'Sign in to your account\')]")));
      try {
      	Thread.sleep(500);
      } catch (InterruptedException e) {
      	e.printStackTrace();
      }
    }
    // 12 | assertText | xpath=//h1 | Welcome!
    assertEquals("Welcome!", driver.findElement(By.xpath("//h1")).getText());
    // 13 | click | id=header-account-menu-link | 
    driver.findElement(By.id("header-account-menu-link")).click();
    // 14 | click | xpath=//a[contains(text(),'Sign out')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign out\')]")).click();
    // 15 | assertText | xpath=//h1 | Sign in to your account
    assertEquals("Sign in to your account", driver.findElement(By.xpath("//h1")).getText());
    // 16 | click | xpath=//a[contains(text(),'Log in')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Log in\')]")).click();
    // 17 | click | xpath=//button | 
    driver.findElement(By.xpath("//button")).click();
    // 18 | assertText | xpath=//div[@id='login']/div/div/form/div/div | Please provide a valid email address.
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.textToBePresentInElementLocated(By.xpath("//div[@id=\'login\']/div/div/form/div/div"), "Please provide a valid email address."));

      assertEquals("Please provide a valid email address.", driver.findElement(By.xpath("//div[@id=\'login\']/div/div/form/div/div")).getText());
    }
    // 19 | assertText | xpath=//div[@id='login']/div/div/form/div[2]/div | Please enter your password.
    assertEquals("Please enter your password.", driver.findElement(By.xpath("//div[@id=\'login\']/div/div/form/div[2]/div")).getText());
  }
}
