// Generated by Selenium IDE
package org.ual.cnsa.jme418;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.*;
import org.openqa.selenium.firefox.*;
import org.openqa.selenium.support.ui.*;
import java.time.Duration;
import java.util.*;

public class SignupTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
	String browser = "";
	Boolean headless = true;
	
	try {
	  browser = System.getProperty("browser");
	} catch (Exception e) {
	  fail("Error in Maven call parameters.");
	}

	switch (browser) {
	  case "firefox":
		FirefoxOptions firefoxOptions = new FirefoxOptions();
		if (headless) firefoxOptions.addArguments("-headless");
		driver = new FirefoxDriver(firefoxOptions);
	
		break;
	  case "chrome":
		ChromeOptions chromeOptions = new ChromeOptions();
		if (headless) chromeOptions.addArguments("--headless=new");
		driver = new ChromeDriver(chromeOptions);
	
		break;
	  default:
		fail("Please select a browser.");
		break;
	}

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void signupNotCheckedTerms() {
    // Test name: signupNotCheckedTerms
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://webapps.cnsa2025-jme418.tech/");
    // 2 | setWindowSize | 1368x759 | 
    driver.manage().window().setSize(new Dimension(1368, 759));
    // 3 | click | xpath=//a[contains(text(),'Sign up')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign up\')]")).click();
    // 4 | type | id=full-name | Joaquín Murcia Escánez
    driver.findElement(By.id("full-name")).sendKeys("Joaquín Murcia Escánez");
    // 5 | executeScript | return new Date().getTime() + "@gmail.com"; | storedMail
    vars.put("storedMail", js.executeScript("return new Date().getTime() + \"@gmail.com\";"));
    // 6 | type | id=email-address | ${storedMail}
    driver.findElement(By.id("email-address")).sendKeys(vars.get("storedMail").toString());
    // 7 | type | id=password | jme418
    driver.findElement(By.id("password")).sendKeys("jme418");
    // 8 | type | id=confirm-password | jme418
    driver.findElement(By.id("confirm-password")).sendKeys("jme418");
    // 9 | click | xpath=//button[@type='submit'] | 
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    // 10 | assertElementPresent | css=.text-danger | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".text-danger"));
      assert(elements.size() > 0);
    }
  }

  @Test
  public void signup() {
    // Test name: signup
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://webapps.cnsa2025-jme418.tech/");
    // 2 | setWindowSize | 1368x759 | 
    driver.manage().window().setSize(new Dimension(1368, 759));
    // 3 | click | xpath=//a[contains(text(),'Sign up')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign up\')]")).click();
    // 4 | type | id=full-name | Joaquín Murcia Escánez
    driver.findElement(By.id("full-name")).sendKeys("Joaquín Murcia Escánez");
    // 5 | executeScript | return new Date().getTime() + "@gmail.com"; | storedMail
    vars.put("storedMail", js.executeScript("return new Date().getTime() + \"@gmail.com\";"));
    // 6 | type | id=email-address | ${storedMail}
    driver.findElement(By.id("email-address")).sendKeys(vars.get("storedMail").toString());
    // 7 | type | id=password | jme418
    driver.findElement(By.id("password")).sendKeys("jme418");
    // 8 | type | id=confirm-password | jme418
    driver.findElement(By.id("confirm-password")).sendKeys("jme418");
    // 9 | click | id=terms-agreement | 
    driver.findElement(By.id("terms-agreement")).click();
    // 10 | click | xpath=//button[@type='submit'] | 
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    // 11 | waitForElementNotPresent | xpath=//h1[contains(.,'Sign in to your account')] | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.invisibilityOfElementLocated(By.xpath("//h1[contains(.,\'Sign in to your account\')]")));
      try {
    	Thread.sleep(1000);
      } catch (InterruptedException e) {
    	e.printStackTrace();
      }
    }
    // 12 | assertText | xpath=//h1 | Welcome!
    assertEquals("Welcome!", driver.findElement(By.xpath("//h1")).getText());
    // 13 | click | id=header-account-menu-link | 
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.elementToBeClickable(By.id("header-account-menu-link")));
      try {
    	Thread.sleep(1000);
      } catch (InterruptedException e) {
    	e.printStackTrace();
      }

      driver.findElement(By.id("header-account-menu-link")).click();
    }
    // 14 | click | xpath=//a[contains(text(),'Sign out')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign out\')]")).click();
    // 15 | assertText | xpath=//h1 | Sign in to your account
    assertEquals("Sign in to your account", driver.findElement(By.xpath("//h1")).getText());
  }

  @Test
  public void signupNotValidMail() {
    // Test name: signupNotValidMail
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://webapps.cnsa2025-jme418.tech/");
    // 2 | setWindowSize | 1368x759 | 
    driver.manage().window().setSize(new Dimension(1368, 759));
    // 3 | click | xpath=//a[contains(text(),'Sign up')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign up\')]")).click();
    // 4 | type | id=full-name | Joaquín Murcia Escánez
    driver.findElement(By.id("full-name")).sendKeys("Joaquín Murcia Escánez");
    // 5 | type | id=password | jme418
    driver.findElement(By.id("password")).sendKeys("jme418");
    // 6 | type | id=confirm-password | jme418
    driver.findElement(By.id("confirm-password")).sendKeys("jme418");
    // 7 | click | id=terms-agreement | 
    driver.findElement(By.id("terms-agreement")).click();
    // 8 | click | xpath=//button[@type='submit'] | 
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    // 9 | assertText | xpath=//div[2]/div | Please enter a valid email address.
    assertEquals("Please enter a valid email address.", driver.findElement(By.xpath("//div[2]/div")).getText());
  }

  @Test
  public void signupNotValidName() {
    // Test name: signupNotValidName
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://webapps.cnsa2025-jme418.tech/");
    // 2 | setWindowSize | 1368x759 | 
    driver.manage().window().setSize(new Dimension(1368, 759));
    // 3 | click | xpath=//a[contains(text(),'Sign up')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign up\')]")).click();
    // 4 | executeScript | return new Date().getTime() + "@gmail.com"; | storedMail
    vars.put("storedMail", js.executeScript("return new Date().getTime() + \"@gmail.com\";"));
    // 5 | type | id=email-address | ${storedMail}
    driver.findElement(By.id("email-address")).sendKeys(vars.get("storedMail").toString());
    // 6 | type | id=password | jme418
    driver.findElement(By.id("password")).sendKeys("jme418");
    // 7 | type | id=confirm-password | jme418
    driver.findElement(By.id("confirm-password")).sendKeys("jme418");
    // 8 | click | id=terms-agreement | 
    driver.findElement(By.id("terms-agreement")).click();
    // 9 | click | xpath=//button[@type='submit'] | 
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    // 10 | assertText | xpath=//form/div/div | Please enter your full name.
    assertEquals("Please enter your full name.", driver.findElement(By.xpath("//form/div/div")).getText());
  }

  @Test
  public void signupNotValidPass() {
    // Test name: signupNotValidPass
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://webapps.cnsa2025-jme418.tech/");
    // 2 | setWindowSize | 1368x759 | 
    driver.manage().window().setSize(new Dimension(1368, 759));
    // 3 | click | xpath=//a[contains(text(),'Sign up')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign up\')]")).click();
    // 4 | type | id=full-name | Joaquín Murcia Escánez
    driver.findElement(By.id("full-name")).sendKeys("Joaquín Murcia Escánez");
    // 5 | executeScript | return new Date().getTime() + "@gmail.com"; | storedMail
    vars.put("storedMail", js.executeScript("return new Date().getTime() + \"@gmail.com\";"));
    // 6 | type | id=email-address | ${storedMail}
    driver.findElement(By.id("email-address")).sendKeys(vars.get("storedMail").toString());
    // 7 | type | id=confirm-password | jme418
    driver.findElement(By.id("confirm-password")).sendKeys("jme418");
    // 8 | click | id=terms-agreement | 
    driver.findElement(By.id("terms-agreement")).click();
    // 9 | click | xpath=//button[@type='submit'] | 
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    // 10 | click | xpath=//div[3]/div | Please enter a password.
    driver.findElement(By.xpath("//div[3]/div")).click();
    // 11 | click | xpath=//div[4]/div | Your password and confirmation do not match.
    driver.findElement(By.xpath("//div[4]/div")).click();
  }

  @Test
  public void signupNotValidPassConf() {
    // Test name: signupNotValidPassConf
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://webapps.cnsa2025-jme418.tech/");
    // 2 | setWindowSize | 1368x759 | 
    driver.manage().window().setSize(new Dimension(1368, 759));
    // 3 | click | xpath=//a[contains(text(),'Sign up')] | 
    driver.findElement(By.xpath("//a[contains(text(),\'Sign up\')]")).click();
    // 4 | type | id=full-name | Joaquín Murcia Escánez
    driver.findElement(By.id("full-name")).sendKeys("Joaquín Murcia Escánez");
    // 5 | executeScript | return new Date().getTime() + "@gmail.com"; | storedMail
    vars.put("storedMail", js.executeScript("return new Date().getTime() + \"@gmail.com\";"));
    // 6 | type | id=email-address | ${storedMail}
    driver.findElement(By.id("email-address")).sendKeys(vars.get("storedMail").toString());
    // 7 | type | id=password | jme418
    driver.findElement(By.id("password")).sendKeys("jme418");
    // 8 | click | id=terms-agreement | 
    driver.findElement(By.id("terms-agreement")).click();
    // 9 | click | xpath=//button[@type='submit'] | 
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    // 10 | click | xpath=//div[4]/div | Your password and confirmation do not match.
    driver.findElement(By.xpath("//div[4]/div")).click();
  }
}
